import {readFileSync,writeFileSync,cpSync,mkdirSync,rmSync,existsSync,readdirSync,statSync} from 'node:fs';
import {resolve,join,relative} from 'node:path';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url));
process.chdir(root);
const config=JSON.parse(readFileSync('site.config.json','utf8'));
const raw=process.env.SITE_URL||config.siteUrl;
if(!raw)throw new Error('Set siteUrl in site.config.json (for example your actual https://PROJECT.pages.dev address), or set the SITE_URL build environment variable.');
const url=new URL(raw);
if(url.protocol!=='https:' || url.username || url.password || url.search || url.hash || url.pathname!=='/')throw new Error('SITE_URL must be an HTTPS origin without a path, credentials, query or fragment.');
writeFileSync('lib/site-deployment.ts',`// Generated by scripts/build-pages.mjs.\nexport const DEPLOYMENT_URL = ${JSON.stringify(url.origin)};\n`);
const result=spawnSync(process.execPath,['scripts/run-framework.mjs','build'],{stdio:'inherit',cwd:root});
if(result.status!==0)process.exit(result.status||1);
const target=resolve(root,'pages-dist');
rmSync(target,{recursive:true,force:true});mkdirSync(target,{recursive:true});
cpSync('dist/client',target,{recursive:true});
const worker=join(target,'_worker.js');mkdirSync(worker,{recursive:true});
cpSync('dist/server',join(worker,'server'),{recursive:true});
// Keep server modules inside _worker.js so they are never uploaded as public assets.
rmSync(join(worker,'server','wrangler.json'),{force:true});
rmSync(join(target,'.assetsignore'),{force:true});
const staticPaths=[];
function walk(dir){for(const name of readdirSync(dir)){const path=join(dir,name);if(statSync(path).isDirectory())walk(path);else staticPaths.push('/'+relative(target,path).split('\\').join('/'));}}
for(const name of readdirSync(target)){if(name==='_worker.js'||name.startsWith('_')&&name!=='_next')continue;const path=join(target,name);if(statSync(path).isDirectory())walk(path);else staticPaths.push('/'+name);}
writeFileSync(join(worker,'index.js'),`import app from './server/index.js';\nconst publicAssets = new Set(${JSON.stringify(staticPaths)});\nexport default {\n async fetch(request, env, ctx) {\n  const path = new URL(request.url).pathname;\n  if (path.startsWith('/_next/static/') || publicAssets.has(path)) return env.ASSETS.fetch(request);\n  return app.fetch(request, env, ctx);\n }\n};\n`);
writeFileSync(join(target,'_routes.json'),JSON.stringify({version:1,include:['/*'],exclude:['/_next/static/*','/fonts/*','/favicon.svg']},null,2)+'\n');
// Vite's Worker build creates a Wrangler redirect. Pages must use the root Pages config.
rmSync(resolve(root,'.wrangler/deploy/config.json'),{force:true});
console.log('Cloudflare Pages output ready: pages-dist');
console.log('Canonical site URL: '+url.origin);
